### PR TITLE
Remove pry

### PR DESCRIPTION
**Pull request by greysteil**
Probably don't want it by default, no?

### CODE REVIEW

**Comment by greysteil** [comment]
@isaacseymour - I've also set up travis to track, so we'll get a build report for this PR.

**Comment by isaacseymour** [comment]
This means you have to explicitly `require 'pry'` whenever you want to use `binding.pry` which is a bit of a pain :/

**Comment by greysteil** [comment]
Yep, but not sure the gem should be opinionated on how to do debugging. Up to you!

**Comment by isaacseymour** [comment]
True!

**Comment by greysteil** [comment]
Failure is unrelated. Should be fixed by https://github.com/gocardless/activejob-retry/pull/8

**Comment by greysteil** [comment]
Also, we'll need to special case on the Ruby version if you want to keep this in. See https://travis-ci.org/gocardless/activejob-retry/jobs/45612172

**Comment by isaacseymour** [comment]
Ugh, definitely not worth it. Let's merge.

**Pull request merged**
